apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readonly-admin
roleRef:
  name: readonly-role 
subjects:
- kind: ServiceAccount
  name: readonly-user 
userNames:
- system:serviceaccount:default:readonly-user


