apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2018-06-19T23:29:49Z
  generation: 1
  labels:
    app: test
  name: test
  namespace: testns
  uid: a91162a6-7418-11e8-8545-42010a8e013d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: simplepy:1.0
        imagePullPolicy: Always
        name: brdsimplepy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

