apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: "default"
  labels:
    serviceName: "simple-test-service"
    owner: "bdastur"
    environment: "development"
  annotations:
    serviceId: "simple-test-service"
spec:
  selector:
    app: "test"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
