apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap 
data:
    testvalue: "Hello World"
    releaseName: {{ quote  .Release.Name }}
    releaseTime: {{ quote  .Release.Time }}
    releaseNamespace: {{ quote .Release.Namespace }}
    releaseService: {{ quote .Release.Serviceee }}
    releaseRevision: {{ quote .Release.Revision }}
    releaseIsUpgrade: {{ quote .Release.IsUpgrade }}
    releaseIsInstall:  "{{ .Release.IsInstall }}"
    drinkChoice: {{ quote .Values.foodChoices.drink }}
    foodChoices: {{ .Values.foodChoices.food | repeat 4 | upper | quote }}
    desertChoice: {{ .Values.foodChoices.desert | quote }}
    desertAlways: {{ .Values.foodChoices.desert | default "cake" | quote }}
    {{ if .Values.foodChoices.drink | quote }}
    glassProvided: "true"
    {{ end }}
    {{ if and (.Values.foodChoices.drink) (eq .Values.foodChoices.drink "tea") }}
    mug: "provided"
    {{end }}
    {{ if .Values.foodChoices.desert | quote }}
    desertPlate: "provided"
    {{ else }}
    sendBill: "true"
    desertPlate: "not provided"
    {{ end }}
    {{ with .Values.foodChoices }}
    scopedFood: {{ .food | quote }}
    scopedDrink: {{ .drink | quote }}
    {{ end }}
    beverages: |-
    {{- range .Values.foodChoices.beverages }}
        {{ . | quote }}
    {{- end }}
    sizes: |-
    {{- range tuple "small" "medium" "large" }}
        {{ . }}
    {{- end }}

{{ indent 4 "testvalue2: A test of indent" }}
