apiVersion: v1
kind: Pod
metadata:
  name: simpleclient
  namespace: default
  labels:
    owner: bdastur
    app: simple-python-client
  annotations:
     podId:  simpleclientpod01
     version: "1.0.1"
spec:
  containers:
  - name: simpleclient 
    image: xxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/examples/simpleclient
    imagePullPolicy: Always 
    ports:
    - containerPort: 80 
    env:
    - name: USER_NAME
      value: "Behzad Dastur"
    # Define environment variable from configmap value
    - name: INITIAL_COUNT
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: initial_count

    # Mount configmap.
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: demo-configmap
      items:
      - key: "initial_count"
        path: "initial_count"
      - key: "app.properties"
        path: "app.properties"


