apiVersion: v1
kind: Pod
metadata:
  name: simpleclient
  namespace: default
  labels:
    owner: bdastur
    app: simple-python-client
  annotations:
     podId:  simpleclientpod01
     version: "1.0.1"
spec:
  containers:
  - name: simpleclient 
    image: xxxx.dkr.ecr.us-east-1.amazonaws.com/examples/simpleclient
    imagePullPolicy: Always 
    ports:
    - containerPort: 80 
