<FloatLayout>:
    Button:
        text: "Button One!"
        size_hint: 0.5, 0.3
        pos_hint: {'top': 1}
    Button:
        text: "Button two!"
        size_hint: 0.5, 0.3
        pos: root.x + 500, root.y + 500
    # Button:
    #     # Only scale horizontally. Button should occupy 80% of width.
    #     text: "Button Two!"
    #     size_hint_x: .8
    #     size_hint_y: 0.5
    #     pos_hint: {'top': 1}


    