<CustomWidget>:
    Label:
        text: "Input Box"
        pos: root.x + 50, root.top - self.height - 20
    TextInput:
        hint_text: "Type something"
        pos: root.x + 200, root.top - self.height - 50
        size: 400, 50
    Button:
        text: "Button one"
        pos: root.x + 50, root.top - self.height - 150
        size: 200, 40
    Button:
        text: "Button two"
        pos: root.x + 350, root.top - self.height - 150
        size: 200, 40
