/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apputils;

public class Display {
    String displayType;

    /*
     * Parameterless constructor
     */
    public Display() {
        displayType = "text";
    }

    public void displayGreeting(String greeting) {
        System.out.println(greeting);
    }

}
