/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstawsapp;

import firstawsapp.Greetings.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Greetings greetings = new Greetings();
        greetings.displayGreeting();
    }
}
