/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstawsapp;

import apputils.Display.* ;


public class Greetings {
    String greetString;

    /*
     * Parameterless constructor
     */
    Greetings() {
        greetString = "Hello world from Greetings!";
    }

    /*
     * Constructor that takes a string
     */
    Greetings(String greeting) {
        if (greeting != null || greeting != "") {
            greetString = greeting;
        } else {
            greetString = "Hello World from Greetings!";
        }
    }

    public String getGreeting() {
        return greetString; 
    }

    public void displayGreeting() {
        apputils.Display display = new apputils.Display();
        display.displayGreeting(greetString);
    }
}
