apiVersion: v1
kind: Pod
metadata:
  name: simpleserver
  namespace: default
  labels:
    owner: bdastur
    environment: development
    app: simpleserver
  annotations:
    appId: "simpleServer01"
spec:
  containers:
  - name: simpleserver 
    image: xxxx.dkr.ecr.us-east-1.amazonaws.com/examples/simpleserver:latest 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8000
     

