apiVersion: v1
kind: Service
metadata:
  name: simpleserverservice 
  namespace: default
  labels:
    serviceName: simpleserverservice
    owner: "bdastur"
    environment: "development"
  annotations:
    serviceId: "simple-test-service"
spec:
  selector:
    app: simpleserver 
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

